---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: distributor
    spec:
      containers:
      - name: distributor
        image:  quay.io/cortexproject/cortex:master-fe16b2bc
        imagePullPolicy: IfNotPresent
        args:
        - -target=distributor
        - -log.level=debug
        - -server.http-listen-port=80
        - -consul.hostname=consul.default.svc.cluster.local:8500
        - -distributor.replication-factor=3
        - -dynamodb.chunk-table.period=168h0m0s
        - -dynamodb.chunk-table.prefix=cortex_chunks_
        ports:
        - containerPort: 80
